source 'https://rubygems.org'
gem 'rails', '>= 6.1.0'
gem 'sqlite3', '>=1.4.0'
gem 'capybara', '>=3.35.0'
gem 'cucumber', '>=5.2.0'
gem 'rspec', '>=3.9.0'
gem 'rake', '~>13.0'
gem 'node-compiler', '>=0.8.0'
gem 'simplecov', '>=0.21.0'
gem 'yarn', '>=0.1.0'
gem 'reek'
gem 'flog'
gem 'saikuro'
gem 'omniauth'